---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- path: jsonpatch.yaml
  target:
    kind: ConfigMap
    name: ca-ldap
    namespace: openshift-config
...
